name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm-flags:
          - "-Xmx512m"
          - "-XX:+UseG1GC"
          - "-XX:+UseStringDeduplication"
          - "-XX:+UseCompressedOops"
          - "-XX:+HeapDumpOnOutOfMemoryError"
          - "-XX:+PrintGCDetails"
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Set up JVM Options
      run: echo "MAVEN_OPTS=${{ matrix.jvm-flags }}" >> $GITHUB_ENV


    - name: Build and Test with Maven
      timeout-minutes: 15
      run: ./mvnw -B verify

    - name: Get JaCoCo Coverage
      id: coverage  
      run: |
        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
        echo "COVERAGE=$coverage" >> $GITHUB_ENV

    - name: Print Coverage
      run: 'echo "Coverage: $COVERAGE%"'

